/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bb;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import java.util.Set;
import java.util.TreeMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import sun.font.TextLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.ListModel;


/**
 *
 * @author Dell
 */
 
       
public class DictionaryApplication extends javax.swing.JFrame {
    
    /**
     * Creates new form DictionaryApplication
     */
    
    public DictionaryApplication() {
        initComponents();
        initData();
    }
    
    
    public void initData(){
        DictionaryManagement DicMan=new DictionaryManagement();
        DicMan.insertFromFile();
        Set<String> keySet=Dictionary.store.keySet();
        DefaultListModel model=new DefaultListModel();
        for (String i:keySet) {
             model.addElement(i);
        }
        jList1.setModel(model);
       
    }
    
       
            
        
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(750, 600));
        setMinimumSize(new java.awt.Dimension(750, 600));
        getContentPane().setLayout(null);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Thêm.png"))); // NOI18N
        jButton3.setText("Thêm từ");
        jButton3.setMaximumSize(new java.awt.Dimension(55, 23));
        jButton3.setMinimumSize(new java.awt.Dimension(55, 23));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(510, 170, 80, 40);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/xoa1.png"))); // NOI18N
        jButton4.setText("Xóa từ");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(330, 230, 80, 40);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 0, 0);

        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jList1MouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(130, 220, 190, 260);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextArea1MouseClicked(evt);
            }
        });
        jTextArea1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextArea1KeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(420, 220, 200, 260);

        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField1MouseClicked(evt);
            }
        });
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(130, 160, 190, 30);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sửa.png"))); // NOI18N
        jButton5.setText("Sửa từ");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(330, 290, 80, 40);

        jLabel2.setText("English");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(400, 90, 50, 20);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(470, 90, 156, 30);

        jLabel4.setText("Vietnamese");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(400, 130, 55, 30);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(470, 130, 156, 30);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/phat am.png"))); // NOI18N
        jButton6.setText("Phát âm");
        getContentPane().add(jButton6);
        jButton6.setBounds(330, 350, 80, 40);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Thoát.png"))); // NOI18N
        jButton7.setText("Exit");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(330, 410, 80, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Eng-Viet2.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(200, 30, 350, 40);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ảnh bìa.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 730, 560);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextArea1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextArea1MouseClicked
       Set<String> keySet=Dictionary.store.keySet();
        DefaultListModel model=new DefaultListModel();
        for(String k: keySet){
            model.addElement(k);
            jList1.setModel(model);
        }
      
    
    }//GEN-LAST:event_jTextArea1MouseClicked

    private void jTextArea1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextArea1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextArea1KeyPressed
    public DictionaryApplication(String para){
       
    }
    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
       String tu=jTextField1.getText();
       DictionaryManagement DicMan=new DictionaryManagement();
        DicMan.insertFromFile();
        int dem=0;
        Set<String> keySet=Dictionary.store.keySet();
       DefaultListModel model=new DefaultListModel();
      int k=tu.length();
            
        for (String i:keySet) {
            if(i.length()>=tu.length()){
            
           
            
            if((i.substring(0,tu.length()).toUpperCase()).equals(tu.toUpperCase())){
                model.addElement(i);
                dem++;
                
            
            }
            }
        
        jList1.setModel(model);
     }
    
        if(dem==0)
            model.addElement("khong tim thay tu");// TODO add your handling code here:
        
                
    }//GEN-LAST:event_jTextField1ActionPerformed
        
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        /*NewJFrame n=new NewJFrame();
        n.setVisible(true);
        
       DictionaryManagement DicMan=new DictionaryManagement();
        DicMan.insertFromFile();*/
        String i=jTextField2.getText();
         String j=jTextField3.getText();
         DictionaryManagement dm=new DictionaryManagement();
          if(null==Dictionary.store.get(i)){
         Dictionary.store.put(i,j);
         JOptionPane.showMessageDialog(this,"Bạn đã thêm từ thành công");
         dm.exportToFile();
         }
          
          else  JOptionPane.showMessageDialog(this,"Từ đã có trong từ điển");
        DefaultListModel model=new DefaultListModel();
        
        Set<String> keySet=Dictionary.store.keySet();
        for (String k:keySet) {
             model.addElement(k);
        }
        jList1.setModel(model);
        
         
         
        
         
         
       
        
         
         
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jList1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseEntered
        
            // TODO add your handling code here:
    }//GEN-LAST:event_jList1MouseEntered

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
         DictionaryManagement DicMan=new DictionaryManagement();
        
        String giatri=jList1.getSelectedValue().toString();
        String a=DicMan.dictionaryLookup(giatri);
        jTextArea1.setText(a);
        // TODO add your handling code here:
    }//GEN-LAST:event_jList1MouseClicked

    private void jTextField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseClicked
       
    }//GEN-LAST:event_jTextField1MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       
         
         DefaultListModel<String> model = (DefaultListModel<String>) jList1
                .getModel();
         
         int click=JOptionPane.showConfirmDialog(rootPane,"Bạn chắc chắn muốn xóa chứ? ");
         if(click==JOptionPane.OK_OPTION){
         String i=jList1.getSelectedValue().toString();
         if (!model.isEmpty() && jList1.getSelectedIndex() >= 0) {
            model.remove(jList1.getSelectedIndex());
            Dictionary.store.remove(i);
            JOptionPane.showMessageDialog(rootPane, "Bạn đã xóa thành công");
            jTextArea1.setText("");
        }
         }
       
        jList1.setModel(model);
        
        DictionaryManagement dm=new DictionaryManagement();
        dm.exportToFile();
         
       
        
        
       
     // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       String i=jList1.getSelectedValue().toString();
        String nghiathay = JOptionPane.showInputDialog("Bạn muốn sửa thành gì: ");
        System.out.println(nghiathay);
        Dictionary.store.replace(i,nghiathay);
        JOptionPane.showMessageDialog(rootPane, "Sửa từ thành công");
        jTextArea1.setText(nghiathay);
        DictionaryManagement dm=new DictionaryManagement();
        dm.exportToFile();
        
        
        
        
        
        /*String i=jTextField2.getText();
        String j=jTextField3.getText();
        DefaultListModel<String> model = (DefaultListModel<String>) jList1
                .getModel();
        Dictionary.store.replace(i, j);
        DictionaryManagement dm=new DictionaryManagement();
        jTextArea1.setText(dm.dictionaryLookup(i));
        dm.exportToFile();
        */
         
        
         // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DictionaryApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DictionaryApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DictionaryApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DictionaryApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DictionaryApplication().setVisible(true);
                
                            

                
            }
            
                       
 
        });
    }
                            
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
